name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm cache
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Project
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Test project
        run: |
          npm test

      - name: Build Project
        run: |
          CI=false npm run build

      - name: Deploy - Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: rls-app-test.raillinksystems.eu
          username: rls-app-test@raillinksystems.eu
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          exclude: .idea
            - node_modules
            - public
            - src
          local-dir: build/

