# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: CI=false npm run build --if-present
    - run: yarn test --passWithNoTests

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: rls-app-test.raillinksystems.eu
        username: rls-app-test@raillinksystems.eu
        password: 'wVY5UfLr'

