name: Research CD Pipeline

on:
  push:
    branches: [ prototypeCICD* ]
  pull_request:
    branches: [ prototypeCICD* ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Build Project
      run: |
        npm install
        CI=false npm run build
        yarn test --passWithNoTests
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: .idea
          - node_modules
          - public
          - src
        local-dir: build/
        server-dir: public_html/
        dry-run: true